### PR TITLE
Remove special path characters from app name in filenames

### LINKED ISSUE #308: App name cannot have special path characters in it
With a package.json with 

    "name": "@mycompany/test-project"

ENOENT: no such file or directory, rename
'/var/folders/8y/ycvpbtbn6nx_552nqm0hkllc0000gn/T/electron-packager/darwin-x64/@mycompany/test-project-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper' -> '/var/folders/8y/ycvpbtbn6nx_552nqm0hkllc0000gn/T/electron-packager/darwin-x64/@mycompany/test-project-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/@mycompany/test-project Helper'

> Which version of electron-packager are you using?

Using electron-packager version 6.0.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

Using command:

    electron-packager . --platform=darwin --arch=x64

This happens no matter which OS I try on and no matter what platform target I use.

> What version of [Electron](http://electron.atom.io) are you building with?

v0.36.9

> What is the host platform are you running electron-packager on?

OS X, Linux

> What target platform(s)/architecture(s) are you building for?

OS X, Linux, Windows

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Steps to reproduce:

1. Name your package to something with a '/' in it
2. Try to run packager

### PR DESCRIPTION
**Pull request by malept**
**Have you read the [section in CONTRIBUTING.md about pull requests](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests)?**

Yes

**Summarize your changes:**

This fixes the problem where an Electron app name contains characters that are invalid in some target platform's filename. The most common case is [Node's scoped packages](https://docs.npmjs.com/misc/scope). The change utilizes the [`sanitize-filename`](https://www.npmjs.com/package/sanitize-filename) module to do all of the filename filtering.

Fixes #308.

**Are your changes appropriately documented?**

I added notes to both `readme.md` and `docs/api.md` saying that invalid characters will be replaced with a hyphen.

**Do your changes have sufficient test coverage?**

I added tests to make sure that binary names for all target platforms are sanitized properly. The OSX test also tests that the `.app` folder name is sanitized appropriately.

**Does the testsuite pass successfully on your local machine?**

Yes

### CODE REVIEW

File: mac.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ class MacApp {
   constructor (opts, stagingPath) {
     this.opts = opts
     this.stagingPath = stagingPath
-    this.appName = opts.name
+    this.appName = common.sanitizeAppName(opts.name)
```
Comment (malept) [inline mac.js]: I think this change may be too heavy-handed - I believe it changes the name shown in the OSX metadata too. I'll have to write a (failing?) test for this.

This is the main reason why I tagged this PR as `[WIP]`.

Comment (malept) [inline mac.js]: OK, now that I've committed https://github.com/electron-userland/electron-packager/pull/455/commits/7cdec7df85e207e476af497c671fd10bef7e01a5 I feel a bit better about the completeness of this PR, and removed the `[WIP]`. Reviews are much appreciated.
